# Generated by Django 4.2.3 on 2023-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='parent_entries',
            field=models.ManyToManyField(blank=True, related_name='sub_entries', to='journal_app.entry'),
        ),
    ]
