# Generated by Django 4.2.5 on 2023-09-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_time',
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_frame', to='journal_app.entry')),
            ],
        ),
    ]
