# Generated by Django 4.2.5 on 2023-09-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_remove_entry_end_time_remove_entry_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeframe',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='time_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry', to='journal_app.timeframe'),
        ),
    ]
