# Generated by Django 4.2.5 on 2023-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0005_remove_timeframe_entry_entry_time_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframe',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
