# Generated by Django 4.2.5 on 2023-09-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0008_entry_title_historicalentry_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalentry',
            name='parent_entries',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='journal_app.entry'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='parent_entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='parent_entries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries', to='journal_app.entry'),
        ),
    ]
