# Generated by Django 4.2.5 on 2023-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0009_historicalentry_parent_entries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalentry',
            name='parent_entries',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='parent_entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='parent_entries',
            field=models.ManyToManyField(blank=True, null=True, related_name='child_entries', to='journal_app.entry'),
        ),
    ]
