# Generated by Django 4.2.5 on 2023-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0010_remove_historicalentry_parent_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='parent_entries',
            field=models.ManyToManyField(blank=True, related_name='child_entries', to='journal_app.entry'),
        ),
    ]
